### ISSUE TITLE
0.4.x: every build fails when numpy/build123d live in the user site-packages (pip install --user)

### ISSUE THREAD

**Issue by M-Stege** [earthtojake/text-to-cad#215]
## Summary

On a machine where the CAD dependencies were installed with `pip install --user`, **every** `scripts/gen` run fails, including a five-line `Box(20, 20, 20)` generator:

```
[scripts/gen] FAILED: AttributeError: module 'numpy.dtypes' has no attribute 'BoolDType'
[scripts/gen]   .../site-packages/build123d/geometry.py:47 in <module>
[scripts/gen]       import numpy as np
[scripts/gen]   .../numpy/_core/_add_newdocs.py:7084 in <module>
[scripts/gen]       add_newdoc('numpy.dtypes', _dtype_name,
```

0.3.13 builds the same sources fine, so this looks like a regression introduced with the closure-capture rework in 0.4.x.

## Root cause

`_run_script_generator_inner()` calls `evict_first_party_modules()` before loading the generator. First-party is decided by `is_first_party_source_file()`, which excludes everything under `_interpreter_roots()` — and that function derives its roots from `sysconfig.get_paths()` plus the `sys.*prefix` values. `sysconfig.get_paths()` returns the **default** scheme, so it never includes the user site-packages (`site.getusersitepackages()`, e.g. `%APPDATA%\Python\Python311\site-packages` on Windows, `~/.local/lib/python3.11/site-packages` on Linux).

Consequently numpy, build123d and OCP are classified as model code and evicted from `sys.modules` on every run. numpy cannot survive a re-import while its C extension is already loaded, which produces the `BoolDType` AttributeError above.

Reproducible check on the affected machine:

```python
from pathlib import Path
import numpy
from cadgen._internal.source_hash import is_first_party_source_file
is_first_party_source_file(Path(numpy.__file__).resolve())  # -> True, expected False
```

The docstring of `evict_first_party_modules()` states that "Runtime and third-party modules (cadgen, build123d, OCP, ...) are never touched", so the intent is clear — the user-site layout simply is not covered. It does not show up in repo development because `CONTRIBUTING.md` builds a `.venv`.

## Environment

- text-to-cad 0.4.5 (Claude Code plugin install)
- Windows 10, CPython 3.11.1 (system install under `C:\Program Files\Python311`)
- numpy 2.4.3, build123d 0.11.1, cadquery-ocp — all installed with `pip install --user`, since the system `site-packages` needs admin rights

## Suggested fix

Add the user-site roots in `_interpreter_roots()` (`cadgen/_internal/source_hash.py`):

```python
import site
...
for user_root in (site.getusersitepackages(), site.getuserbase()):
    if user_root:
        with contextlib.suppress(OSError):
            roots.add(Path(user_root).resolve())
```

With that patch applied, both the minimal box and an 84-part assembly build correctly again, and the resulting STEP matches the 0.3.13 output apart from the `cadgen`/`cadpy` metadata strings.

A more defensive variant would be to never evict a module whose package already owns an imported C extension, but adding the user-site roots covers the standard `pip install --user` layout, which is the common case on Windows machines without admin rights.

**Comment by earthtojake** [comment]
Investigating!

**Comment by M-Stege** [comment]
@
Can confirm 0.4.8 fixed it for me - no local patch needed anymore. Same Windows machine as in the report (everything installed with pip install --user, no admin rights). Test cube builds, and our real project (an ~85 part furniture assembly) builds again end to end, STEP output matches the old one. Thanks for the quick fix!
@
